version: '2'
services:
    php-fpm:
        build: ./php-fpm
        volumes:
            - ./project:/var/www/html:rw
        links:
            - "redis"
            - "mysql"
        networks:
            - frontend
            - backend
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        volumes:
            - ./project:/var/www/html:ro
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/conf/conf.d:/etc/nginx/conf.d:ro
        links:
            - "php-fpm"
        networks:
            - frontend
    redis:
        build: ./redis
        ports:
            - "6379:6379"
        networks:
            - backend
    mysql:
        build: ./mysql
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/log:/var/log
        networks:
            - backend
networks:
    frontend:
    backend:
